package icon

import com.example.design_system.R

data class Outline(
    val arrowLeft: Int,
    val magicStick: Int,
    val home: Int,
    val userSquare: Int,
    val add: Int,
    val altArrowLeft: Int,
    val altArrowRight: Int,
    val arrowRightUp: Int,
    val cake: Int,
    val xClose: Int,
    val dangerTriangle: Int,
    val eyeClosed: Int,
    val eyeOpened: Int,
    val folder: Int,
    val grid: Int,
    val history: Int,
    val location: Int,
    val lock: Int,
    val microphone: Int,
    val plus: Int,
    val rowVertical: Int,
    val search: Int,
    val star: Int,
    val user: Int,
)
val outlineIcons = Outline(
    arrowLeft = R.drawable.outline_arrow_left,
    magicStick = R.drawable.outline_magic_stick,
    home = R.drawable.outline_home,
    userSquare = R.drawable.outline_user_square,
    add = R.drawable.outline_add,
    altArrowLeft = R.drawable.outline_alt_arrow_left,
    altArrowRight = R.drawable.outline_alt_arrow_right,
    arrowRightUp = R.drawable.outline_arrow_right_up,
    cake = R.drawable.outline_cake,
    xClose = R.drawable.outline_x,
    dangerTriangle = R.drawable.outline_danger_triangle,
    eyeClosed = R.drawable.outline_eye_closed,
    eyeOpened = R.drawable.outline_eye_opened,
    folder = R.drawable.outline_folder,
    grid = R.drawable.outline_grid,
    history = R.drawable.outline_history,
    location = R.drawable.outline_location,
    lock = R.drawable.outline_lock,
    microphone = R.drawable.outline_microphone,
    plus = R.drawable.outline_plus,
    rowVertical = R.drawable.outline_row_vertical,
    search = R.drawable.outline_search,
    star = R.drawable.outline_star,
    user = R.drawable.outline_user
)
