name: CD - Deploy to Firebase App Distribution

on:
  push:
    branches: [ develop ]

permissions:
  checks: write
  pull-requests: write
  contents: write

jobs:
  deploy:
    name: 📱 Distribute Release APK to Firebase App Distribution
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Updated to latest version

      - name: Set up JDK 17
        uses: actions/setup-java@v4 # Updated to latest version
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle # Enable Gradle caching

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-cache-${{ hashFiles('**/gradle-wrapper.properties', '**/*.gradle*', '**/settings.gradle*', '**/libs.versions.toml') }}
          restore-keys: |
            gradle-cache-${{ runner.os }}-
            gradle-cache-

      - name: Save Service Account Key
        env:
          FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
        run: echo "$FIREBASE_SERVICE_ACCOUNT_KEY" > app/service-account-key.json

      - name: Create google-services.json
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 -d > app/google-services.json

      - name: Create keys.properties
        run: |
          echo "BEARER_TOKEN=${{ secrets.BEARER_TOKEN }}" > keys.properties
          mkdir -p data
          echo "TMDB_API_KEY=\"${{ secrets.TMDB_API_KEY }}\"" > data/keys.properties

      - name: Create Keystore
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 -d > app/my-release-key.jks
          echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> keystore.properties
          echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> keystore.properties
          echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> keystore.properties

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease --stacktrace --info -Dorg.gradle.jvmargs=-Xmx4g
      - name: Set Release Notes
        id: set-release-notes
        run: |
          echo "RELEASE_NOTES=Push to develop: ${{ github.sha }}" >> $GITHUB_ENV

      - name: Distribute Release APK to Firebase App Distribution
        run: ./gradlew appDistributionUploadRelease --stacktrace
        env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}