name: CI/CD - Push to Develop

on:
  push:
    branches: [ develop ]

permissions:
  checks: write
  pull-requests: write
  contents: write

jobs:
  deploy:
    name: 📱 Distribute Debug APK to Firebase App Distribution
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Create local.properties with TMDB_API_KEY
        run: |
            echo "sdk.dir=/usr/local/lib/android/sdk" > local.properties
            echo "TMDB_API_KEY=${{ secrets.TMDB_API_KEY }}" >> local.properties

      - name: Save Service Account Key
        env:
          FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
        run: echo "$FIREBASE_SERVICE_ACCOUNT_KEY" > service-account-key.json

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Distribute Debug APK to Firebase App Distribution
        run: ./gradlew appDistributionUploadDebug --stacktrace
        env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}