name: CI – Test Coverage Check

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  test-coverage:
    name: Run Unit Tests + Coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Create mock google-services.json
        run: |
          echo '{
            "project_info": {
              "project_number": "123456789",
              "firebase_url": "https://mock-project.firebaseio.com",
              "project_id": "mock-project-id",
              "storage_bucket": "mock-project.appspot.com"
            },
            "client": []
          }' > app/google-services.json
      - name: Generate keys.properties
        run: |
          echo "BEARER_TOKEN=${{ secrets.BEARER_TOKEN }}" > keys.properties
      - name: Run Coverage
        run: |
            chmod +x gradlew
      - name: Clean project
        run: ./gradlew clean
   

      - name: Run unit tests + Kover
        run: ./gradlew test koverVerify koverXmlReport koverHtmlReport -PdisableGoogleServices=true