name: CI/CD - Build, Coverage

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: 🛠️ Compile Project
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up JDK
          uses: actions/setup-java@v4
          with:
            distribution: 'zulu'
            java-version: '21'

        - name: Set up Gradle
          uses: gradle/gradle-build-action@v3

        - name: Clean Project
          run: ./gradlew clean

        - name: Compile Project
          run: ./gradlew assemble

        - name: Make gradlew executable
          run: chmod +x ./gradlew

        - name: Build (assembleDebug)
          run: ./gradlew assembleDebug

  test_coverage:
    name: ✅ Unit Test & Coverage Check
    runs-on: ubuntu-latest
    needs: compile  # only run if compile succeeds

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Verify JaCoCo Coverage
        run: ./gradlew jacocoTestCoverageVerification

      - name: Generate JaCoCo Test Report
        run: ./gradlew jacocoTestReport

      - name: Upload JaCoCo HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-html
          path: build/reports/jacoco/test/html

      - name: Comment on coverage for current branch
        if: github.event_name == 'pull_request' && github.base_ref == 'develop'
        uses: madrapps/jacoco-report@v1.7.1
        with:
          paths: |
            build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 0
          min-coverage-changed-files: 0
          update-comment: true
          title: "🛡️ Code Coverage Report"
          check-for-current-branch: true
          coverage-counter-type: LINE,INSTRUCTION,BRANCH,METHOD,CLASS
          include-all-sources: true
          debug-mode: true
          fail-if-coverage-less: true
          fail-on-coverage-violation: true
          failure-message: "Code coverage is currently at {coverage}%. Target is 100%."
          success-message: "✅ Code coverage is at {coverage}%."
          report-on-status: true
